import Head from "next/head";
import React, { useState } from "react";

const crew = (props) => {
  const crewData = props.crew;
  const [current, setCurrent] = useState(0)

  const dotNav = [];

  const currentDisplayData = i => {
    setCurrent(i)
  }

  for (let i = 0; i < crewData.length; i++) {
    dotNav.push(<button key={i} onClick={event => currentDisplayData(i)} className={`bg-white rounded-full w-[10px] h-[10px] lg:w-[15px] lg:h-[15px] transition-all hover:opacity-50 ${i === current ? "hover:opacity-100" : "opacity-10" }`}><span className="hidden">{i}</span></button>)
  }

  return (
    <>
      <Head>
        <title>Crew</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.svg" />
      </Head>
      <section className='min-h-screen bg-[url("/images/bg-crew-mobile.jpg")] sm:bg-[url("/images/bg-crew-tablet.jpg")] lg:bg-[url("/images/bg-crew.jpg")] bg-cover bg-no-repeat bg-center'>
        <div className="container pt-[5.5rem] sm:pt-[8.5rem] lg:pt-[13.25rem] pb-20 sm:pb-0 text-center lg:text-left md:mx-auto">
          <h5 className="subtitle px-9">
            <span className="opacity-25">02</span>
            meet your crew
          </h5>

          {crewData.map((crew, index) => (
            <div key={index} className={`text-blue px-6 ${index === current ? "flex flex-col sm:flex-col-reverse lg:flex-row-reverse sm:gap-y-10 lg:items-center lg:gap-x-10" : "hidden"}`}>
              <div className="relative h-56 sm:h-[33.25rem] mx-auto">
                <Image
                  src={crew.image}
                  alt={crew.name}
                  width={0}
                  height={0}
                  sizes="100vw"
                  className="w-full h-full"
                  priority
                />
              </div>
              
              <div className="w-full h-px bg-[#383B4B] sm:hidden" />

              <div className="flex flex-col sm:flex-col-reverse gap-8 mt-8 sm:px-[5.5rem] lg:w-1/2 lg:px-0 lg:justify-between">
                <div className="flex justify-center lg:justify-start lg:pt-20 gap-x-4 lg:gap-x-6">
                  {dotNav}
                </div>

                <div className="content lg:h-[35vh]">
                  <div className="uppercase">
                      <h4 className="heading4 sm:mb-4">{crew.position}</h4>
                      <h3 className="heading3">{crew.name}</h3>
                  </div>

                  <p className="mt-4 sm:mt-5 lg:mt-7 lg:w-[27.75rem] body-text">{crew.about}</p>
                </div>

              </div>
            </div>
          ))}
        </div>
      </section>
    </>
  );
};

export default crew;

// Fetching data from local JSON
import fsPromises from "fs/promises";
import path from "path";
import Image from "next/image";
export async function getStaticProps() {
  const filePath = path.join(process.cwd(), "json/crewData.json");
  const jsonData = await fsPromises.readFile(filePath);
  const objectData = JSON.parse(jsonData);

  return {
    props: objectData,
  };
}
