import Head from "next/head";
import Homepage from "@/pages/Homepage";



export default function Home() {
  return (
    <>
      <Head>
        <title>Space Tourism</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.svg" />
      </Head>
      <main>
        <Homepage />
      </main>
    </>
  );
}
