import Head from "next/head";
import React, { useState } from "react";

const Technology = (props) => {
  const techData = props.technology
  const [current, setCurrent] = useState(0)

  const displayData = (i) => {
    setCurrent(i)
  }

  const buttonNumber = []

  for (let i = 0; i < techData.length; i++) {
    buttonNumber.push(<button key={i} className={`rounded-full border border-solid border-white w-10 h-10 sm:w-[3.75rem] sm:h-[3.75rem] lg:w-20 lg:h-20 sm:text-2xl lg:text-[2rem] flex items-center place-content-center transition-all hover:border-white ${i === current ? 'border-opacity-100 bg-white text-black' : 'border-opacity-25'}`} onClick={event => displayData(i)}>{i+1}</button>)
  }

  return (
    <>
      <Head>
        <title>Technology</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.svg" />
      </Head>
    <section className='min-h-screen bg-[url("/images/bg-technology-mobile.jpg")] sm:bg-[url("/images/bg-technology-tablet.jpg")] lg:bg-[url("/images/bg-technology.jpg")] bg-cover bg-center bg-no-repeat lg:relative'>
      <div className="sm:container py-20 sm:pt-[8.5rem] lg:pt-[13.25rem] md:mx-auto">
        <h5 className="subtitle px-9">
          <span className="opacity-25">03</span>
          space launch 101
        </h5>

        {techData.map((tech, index) => (
          <div key={index} className={`text-white ${index === current ? 'flex flex-col lg:flex-row-reverse lg:items-center lg:justify-end lg:pt-20 lg:pb-20' : 'hidden'}`}>
            <div className="h-44 sm:h-[19.4rem] lg:h-[32.95rem] lg:absolute lg:right-0">
              <Image 
                src={tech.image}
                alt={tech.title}
                width={0}
                height={0}
                sizes='100vw'
                className='w-full h-full'
                priority
              />
            </div>

            <div className="flex flex-col lg:w-7/12 lg:flex-row lg:items-center xl:gap-x-20">
              <div className="flex justify-center gap-x-4 mt-9 mb-7 sm:mb-11 btn-number lg:flex-col lg:gap-y-8">
                {buttonNumber}
              </div>
              
              <div className="text-center px-6 lg:text-left">
                <p className="subheading2 mb-2 sm:mb-6">THE TERMINOLOGY...</p>
                <h3 className="heading3 uppercase mb-4 sm:mb-6">{tech.title}</h3>
                <p className="body-text md:w-8/12 lg:w-[80%] md:mx-auto lg:mx-0">{tech.description}</p>
              </div>
            </div>

          </div>
        ))}
      </div>
    </section>
    </>
  );
};

export default Technology;


// Fetch data from local JSON
import fsPromise from 'fs/promises'
import path from 'path'
import Image from "next/image";
export async function getStaticProps() {
  const filePath = path.join(process.cwd(), 'json/technologyData.json')
  const jsonData = await fsPromise.readFile(filePath)
  const objectData = JSON.parse(jsonData)

  return {
    props: objectData
  }
}
